import { describe, it } from "node:test";
import assert from "node:assert/strict";
import * as sdk from "./index.js";

const EXPECTED_EXPORTS = [
  "ASSET_FIXTURES",
  "ASSET_AUCTION_SCHEMA_ID",
  "ASSET_AUCTION_SCHEMA_REF",
  "AssetConfigError",
  "KeeperStatusClient",
  "MAINNET_ARTIFACTS",
  "MAINNET_CONFIRM_PHRASE",
  "MAINNET_DEPLOY_MIN_XLM_STROOPS",
  "MAINNET_MICRO_MAX_ESCROW",
  "MAINNET_MIN_FEE_RESERVE_STROOPS",
  "MAX_AUDITOR_BLOB_BYTES",
  "MAX_CIPHERTEXT_BYTES",
  "MAX_V2_PARTICIPANTS",
  "RECEIPT_VERSION",
  "SEALED_PROPOSAL_SCHEMA_ID",
  "SEALED_PROPOSAL_SCHEMA_REF",
  "RoundContract",
  "RoundErrors",
  "StatusApiError",
  "SubRosaClient",
  "SubRosaClientConfigError",
  "SubRosaMissingReturnValueError",
  "SubRosaNetworkMismatchError",
  "SubRosaPreflightError",
  "SubRosaSubmitError",
  "SubRosaTimeoutError",
  "SubRosaTransactionError",
  "assertMainnetConfirmed",
  "assertMicroAmounts",
  "assertReadinessForExecute",
  "assetAuctionRound",
  "contractErrorCode",
  "createOzChannelsSubmitter",
  "createOzChannelsSubmitterFromEnv",
  "createSacBalanceReader",
  "createAssetAuctionRound",
  "createSealedProposalRound",
  "decodeSealedProposal",
  "defaultMainnetReadinessInput",
  "evaluatePreflight",
  "encodeSealedProposal",
  "fetchContractWasmHash",
  "fetchKeeperStatus",
  "formatReadinessReport",
  "hasBlockingFailures",
  "nativeXlmSacId",
  "networkFingerprint",
  "normalizeRoundId",
  "normalizeSorobanContractId",
  "parseReceipt",
  "redactReceipt",
  "runMainnetReadiness",
  "serializeReceipt",
  "sealAssetBid",
  "sealProposal",
  "sealedProposalRound",
  "tryDecodeBase64",
  "tryDecodeHex",
  "validateAssetConfig",
  "validateAssetConfigs",
  "validateEncryptedBlob",
  "validateContractNetwork",
  "verifyReceipt",
  "verifySettledRoundProof",
];

describe("SDK public API snapshot", () => {
  it("should match the expected named exports", () => {
    const actual = Object.keys(sdk).sort();
    const expected = [...EXPECTED_EXPORTS].sort();
    assert.deepEqual(actual, expected);
  });
});
